Repository brylie/language-lesson-chat, pull requests merged in 2024-09, with the labels that each got.

#28 Add minigames app and improve UX
  .editorconfig
  app/.env.example
  app/core/settings/base.py
  app/lessons/migrations/0009_rename_lesson_chatlesson.py
  app/lessons/migrations/0010_chatlesson_minigames.py
  app/lessons/migrations/0011_alter_chatlesson_minigames.py
  app/lessons/models.py
  app/lessons/templates/lessons/chat_lesson.html
  app/minigames/__init__.py
  app/minigames/admin.py
  app/minigames/apps.py
  app/minigames/blocks.py
  app/minigames/migrations/__init__.py
  app/minigames/models.py
  app/minigames/static/js/step_order_game.js
  app/minigames/templates/minigames/blocks/step_order_game.html
  app/minigames/tests.py
  app/minigames/views.py
  app/transcripts/models.py
  minigames/job_task_game/assets/espresso.webp
  minigames/job_task_game/assets/grind_beans.webp
  minigames/job_task_game/assets/pull_shot.webp
  minigames/job_task_game/assets/tamp_grounds.webp
  minigames/job_task_game/job_task_game.html
  minigames/job_task_game/job_task_game.js
Labels: enhancement, Review effort [1-5]: 3, tests

#25 Added the logo in the top left
  app/branding/__init__.py
  app/branding/admin.py
  app/branding/apps.py
  app/branding/migrations/0001_initial.py
  app/branding/migrations/__init__.py
  app/branding/models.py
  app/branding/tests.py
  app/branding/views.py
  app/branding/wagtail_hooks.py
  app/core/settings/base.py
  app/core/static/css/core.css
  app/core/templates/base.html
Labels: documentation, enhancement, Review effort [1-5]: 2

#31 Update homepage styling and navigation
  app/core/templates/base.html
  app/core/templates/navbar.html
  app/home/static/css/welcome_page.css
  app/home/templates/home/home_page.html
  app/home/templates/home/welcome_page.html
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#32 Allow orderable key concepts
  app/lessons/migrations/0012_alter_keyconcept_options_keyconcept_sort_order.py
  app/lessons/models.py
Labels: enhancement, Review effort [1-5]: 2

#35 Move minigame to lesson success page
  app/lessons/templates/lessons/chat_lesson.html
  app/lessons/templates/lessons/lesson_success.html
  app/minigames/templates/minigames/blocks/step_order_game.html
Labels: enhancement, Review effort [1-5]: 2

#36 Add iframe minigame
  app/lessons/migrations/0013_alter_chatlesson_minigames.py
  app/lessons/models.py
  app/lessons/templates/lessons/lesson_success.html
  app/minigames/blocks.py
  app/minigames/static/css/minigames.css
  app/minigames/templates/minigames/blocks/iframe_block.html
  app/minigames/templates/minigames/minigames.html
Labels: documentation, enhancement, Review effort [1-5]: 3

#37 Add django-registration
  app/accounts/forms.py
  app/accounts/templates/django_registration/activation_complete.html
  app/accounts/templates/django_registration/activation_email_body.txt
  app/accounts/templates/django_registration/activation_email_subject.txt
  app/accounts/templates/django_registration/activation_failed.html
  app/accounts/templates/django_registration/registration_closed.html
  app/accounts/templates/django_registration/registration_complete.html
  app/accounts/templates/django_registration/registration_form.html
  app/accounts/templates/registration/login.html
  app/core/settings/base.py
  app/core/templates/navbar.html
  app/core/urls.py
  app/requirements.txt
Labels: documentation, enhancement, Review effort [1-5]: 3

#38 Add chat summary flow and refactor code for simplicity
  app/lessons/migrations/0014_alter_chatlesson_options_alter_chatlesson_table.py
  app/lessons/models.py
  app/lessons/templates/lessons/chat_interface.html
  app/lessons/templates/lessons/chat_summary.html
  app/lessons/templates/lessons/combined_htmx_response.html
Labels: documentation, enhancement, Review effort [1-5]: 3

#39 Add BaseMinigameBlock
  app/lessons/migrations/0015_alter_chatlesson_minigames.py
  app/minigames/blocks.py
Labels: enhancement, Review effort [1-5]: 2

#41 Update iframe CSS styling
  app/minigames/static/css/minigames.css
  app/minigames/templates/minigames/blocks/iframe_block.html
  app/minigames/templates/minigames/minigame.html
Labels: enhancement, Review effort [1-5]: 2, formatting

#44 Add login_required decorator on ChatLesson.serve
  app/lessons/models.py
Labels: enhancement, Review effort [1-5]: 1

#47 Update sidebar to reduce similarity to advertisements
  app/lessons/templates/lessons/chat_summary.html
Labels: enhancement, Review effort [1-5]: 2

#48 Fix transcript display issue after minigame
  app/lessons/models.py
Labels: Bug fix, Review effort [1-5]: 1

#49 Move key concepts and tweak prompt
  app/lessons/templates/lessons/chat_lesson.html
  app/lessons/templates/lessons/prompt_template.txt
Labels: documentation, enhancement, Review effort [1-5]: 2

#51 Fix IFrame minigame to not pre-populate empty query params block
  app/minigames/blocks.py
Labels: Review effort [1-5]: 2, Bug fix

#52 Add translation support and update language strings
  app/home/templates/home/home_page.html
  app/lessons/templates/lessons/chat_interface.html
  app/lessons/templates/lessons/chat_lesson.html
  app/lessons/templates/lessons/chat_response.html
  app/lessons/templates/lessons/chat_summary.html
  app/lessons/templates/lessons/combined_htmx_response.html
  app/lessons/templates/lessons/key_concepts_grid.html
  app/lessons/templates/lessons/suggested_responses.html
  app/minigames/templates/minigames/minigame.html
Labels: documentation, enhancement, Review effort [1-5]: 3
